AWSTemplateFormatVersion: 2010-09-09
Description: Creates SSM parameter

Parameters:
  Name:
    Type: String
  Value:
    Type: String
  Value2: 
    Type: String
    Default: ''
  Type:
    Default: String
    Type: String
  Description:
    Type: String

Conditions:
  HasValue2: !Not [!Equals [!Ref Value2, '']]
  
Resources:
  SSMParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Description: !Ref Description
      Name: !Ref Name
      Type: !Ref Type
      Value: !If [HasValue2, !Join ['', [!Ref Value, !Ref Value2]], !Ref Value]

Outputs:
  ParamName:
    Value: !Ref SSMParameter
  ParamType:
    Value: !GetAtt SSMParameter.Type
  ParamValue:
    Value: !GetAtt SSMParameter.Value
