template:
  path: ssm/parameter.yaml
parameters:
    Name: /omni-epay-integration/{{ stack_group_config.environment }}/DB_PASSWORD
    Value: 'QMf9Kf7gXQ8K'
    Description: DB_PASSWORD - {{ stack_group_config.environment }}
stack_tags: