template:
  path: ssm/parameter.yaml
parameters:
    Name: /omni-epay-integration/{{ stack_group_config.environment }}/EPAY_PASSWORD
    Value: '39ezB7rq!6N'
    Description: EPAY_PASSWORD - {{ stack_group_config.environment }}
stack_tags: