template:
  path: ssm/parameter.yaml
parameters:
    Name: /omni-epay-integration/{{ stack_group_config.environment }}/DB_HOST
    Value: 'omni-dw-prod-1.csqnwcsrz7o6.us-east-1.rds.amazonaws.com'
    Description: DB_HOST - {{ stack_group_config.environment }}
stack_tags: